### PR TITLE
Update to v1.1.8

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged) `NA`
* [x] Reset the build number to `0` (if the version changed) `YES`
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sugatoray** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
## Build Failure

This will fail until the `lazy_loader` package is available on conda-forge. The following PR was created to bring the library onto conda-forge.

- https://github.com/conda-forge/staged-recipes/pull/18639

**Comment by sugatoray** [comment]
## Note :fire:

Once this PR is merged, the other PR #6 can be closed without merging.

**Comment by sugatoray** [comment]
## ToDo :bulb:

Once the feedstock for `lazy_loader` is created, update the recipe here as follows.

See this comment to update the recipe here.

- https://github.com/conda-forge/staged-recipes/pull/18639#discussion_r854679972

> - Target a pre-release channel for `lazy_loader`: https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds
> - If the recipe is non rc the normal selection will apply, meaning that mamba will select the highest number from both channels or focus on whichever channel you have as your first one as determined by your settings: [mamba.readthedocs.io/en/latest/advanced_usage/package_resolution.html](https://mamba.readthedocs.io/en/latest/advanced_usage/package_resolution.html)

:point_right:  **Add the following to `recipe/conda_build_config.yaml`**

```yml
# file: recipe/conda_build_config.yaml
channel_sources:
  - conda-forge/label/lazy_loader_rc,conda-forge
```

### Note: `lazy_loader` is available now on a `conda-forge rc channel`

:point_right:  Until there is a non `rc`-version available on PyPI, the conda-forge package of `lazy_loader` will also be made available on a `rc` channel (`conda-forge/label/lazy_loader_rc`).

```sh
conda search -c conda-forge/label/lazy_loader_rc lazy_loader
Loading channels: done
# Name                       Version           Build  Channel             
lazy_loader                   0.1rc2    pyh0de9830_0  conda-forge/label/lazy_loader_rc
```

**Comment by sugatoray** [comment]
@BastianZim Some help with setting up the `rc` version of `lazy_loader` will be helpful. Thank you.

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Hmm, strange. Anyways, I would first rerender and then see what the error is.

**Comment by sugatoray** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
### Build Error Reason

[(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=514636&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=115)

```sh
Mamba failed to solve:
 - pip
 - biopython
 - pandas
 - multipledispatch
 - pytest
 - python-codon-tables
 - scikit-learn
 - pytest-regtest
 - lazy_loader
 - numpy
 - weblogo
 - pillow
 - python >=3.6
 - requests

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested lazy_loader
```

:point_right: The fix is to add `lazy_loader` to host-requirements as well.

> :fire: My observation is that if you see `nothing provides <some_package>` in the error, despite adding it to the run-requirements and making sure that `<some_package>` is available on conda-forge, the fix that often works is to add `<some-package>` to host-requirements as well.
> :star: Most likely what is happening is that somehow the packaging of the target PyPI library requires `<some_package>` as a build dependency and unless it is present in the host system, conda-forge cannot build it.

@BastianZim

**Pull request merged**
